version: '3'

services:
  cron:
    build: ./cron
    volumes:
      - ./cron/scripts:/scripts
      - ./cron/crontabs:/var/spool/cron/crontabs
  flask:
    build: ./flask
    command: uwsgi --socket 0.0.0.0:3031 --chdir /app --wsgi-file main.py --callable app --master --processes 4 --threads 2
    environment:
      CHANNEL_ACCESS_TOKEN: $CHANNEL_ACCESS_TOKEN
      CHANNEL_SECRET: $CHANNEL_SECRET
    volumes:
      - ./flask/app:/app
  nginx:
    image: nginx:latest
    ports:
      - '5000:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - flask
