FROM alpine

RUN apk --update add tzdata && \
  cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
  apk del tzdata && \
  rm -rf /var/cache/apk/*

RUN apk add curl

COPY crontabs/* /var/spool/cron/crontabs/
RUN chmod 600 /var/spool/cron/crontabs/*

CMD crond -l 2 -f
