FROM python:3.8.5-alpine

WORKDIR /app
ENV FLASK_APP=main.py

RUN pip install Flask
RUN pip install line-bot-sdk
RUN pip install python-jose
RUN pip install schedule

CMD [ "flask", "run", "--host=0.0.0.0", "--debugger", "--reload" ]
