FROM python:3.8.5-alpine

WORKDIR /app
ENV FLASK_APP=main.py

RUN apk add gcc build-base linux-headers

RUN pip install Flask
RUN pip install uwsgi
RUN pip install line-bot-sdk

CMD [ "flask", "run", "--host=0.0.0.0", "--debugger", "--reload" ]
